version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: testu
      POSTGRES_USER: testup
      POSTGRES_DB: stream
    ports:
    - 5432:5432
    volumes:
    - ./:/docker-entrypoint-initdb.d/
  app:
    build: .
    command: ["go", "run", "stream.go"]
    volumes:
    - ./:/var/lib/go/src/github.com/SArtemJ/GoStreamControlAPI
    ports:
    - 8000:8000
    depends_on:
    - db
